# Sports14 Text/Image Feature Extraction

In [2]:

import os
import numpy as np
import pandas as pd

In [3]:
os.chdir('/home/minhle/CaMRec/data')
os.getcwd()

'/home/minhle/CaMRec/data'

## Load text data

In [4]:
i_id, desc_str = 'itemID', 'description'

file_path = './'
file_name = 'meta-baby.csv'

meta_file = os.path.join(file_path, file_name)

df = pd.read_csv(meta_file)
df.sort_values(by=[i_id], inplace=True)

print('data loaded!')
print(f'shape: {df.shape}')

df[:3]

data loaded!
shape: (7050, 10)

,itemID,asin,categories,description,title,price,imUrl,brand,related,salesRank
0,0,097293751X,[['Baby']],Easily keep track of your baby's or child's da...,"Baby Tracker&reg; - Daily Childcare Journal, S...",17.00,http://ecx.images-amazon.com/images/I/41Bb6wf%...,Time Too,"{'also_bought': ['9729375011', 'B004FN1AE8', '...",NaN
1,1,9729375011,[['Baby']],This is version of the award-winningBaby Track...,Newborn Baby Tracker&reg; - Round the Clock Ch...,15.95,http://ecx.images-amazon.com/images/I/51r3BLpL...,NaN,"{'also_bought': ['B000V5KPZ4', 'B001F8TLLU', '...",NaN
2,2,B00000IZQI,[['Baby']],This colorful car collection develops motor sk...,Fisher Price Nesting Action Vehicles,8.37,http://ecx.images-amazon.com/images/I/51E83QCC...,NaN,"{'also_bought': ['B0042D69W4', 'B00428LIZM', '...",NaN

In [5]:

# sentences: title + brand + category + description | All have title + description

title_na_df = df[df['title'].isnull()]
print(title_na_df.shape)

desc_na_df = df[df['description'].isnull()]
print(desc_na_df.shape)

na_df = df[df['description'].isnull() & df['title'].isnull()]
print(na_df.shape)

na3_df = df[df['description'].isnull() & df['title'].isnull() & df['brand'].isnull()]
print(na3_df.shape)

na4_df = df[df['description'].isnull() & df['title'].isnull() & df['brand'].isnull() & df['categories'].isnull()]
print(na4_df.shape)

(13, 10)
(664, 10)
(13, 10)
(13, 10)
(0, 10)

In [6]:

df[desc_str] = df[desc_str].fillna(" ")
df['title'] = df['title'].fillna(" ")
df['brand'] = df['brand'].fillna(" ")
df['categories'] = df['categories'].fillna(" ")

In [7]:
sentences = []
for i, row in df.iterrows():
    sen = row['title'] + ' ' + row['brand'] + ' '
    cates = eval(row['categories'])
    if isinstance(cates, list):
        for c in cates[0]:
            sen = sen + c + ' '
    sen += row[desc_str]
    sen = sen.replace('\n', ' ')

    sentences.append(sen)

sentences[:10]

["Baby Tracker&reg; - Daily Childcare Journal, Schedule Log Time Too Baby Easily keep track of your baby's or child's daily schedules, activities and needs in one handy spot.  And make the drop-off and pick-up process for childcare a snap.  The Baby Tracker Daily Childcare Journal is designed to make it fast and easy to record and review meals, naps, activities, playtime, daily news, milestones and to-dos ---all in a single page view.  Get ready for doctor visits, give to childcare helpers and use this easy at-a-glance daily record to monitor schedules and prep for your baby's daily needs.  This version records daily activities from 6 a.m. to 7 p.m. and creates a visual snapshot of activities by time each day.   The Baby Tracker Daily Childcare Journal is ready to keep track of up to 6 months of daily schedule tracking (180 days) and is spiral bound to make it portable and lay flat for easy recording on a countertop or nightstand.Each journal includes:*180 daily at-a-glance tracking records (90 pages)* Key Contacts List* Medical Emergency Form and Instructions* Health Facts and Immunization Record* Printed on high quality, easy writing, bright white, 100% recycled paperBirth/3months to 3 years(**PLEASE NOTE: The Newborn Baby Tracker journal is also available for night AND day schedule tracking for nursing moms and 24-hour newborns.)MUST USE.  Pick up where the caregiver leaves off.  Now every nap and bottle can be chronicled with Baby Tracker, an at-a-glance charting system. -Working MotherKEEP TRACK OF BABY.  The Baby Tracker from Time Too is by far the simplest, most stylish, most no-nonsense planner we've seen. -American BabyFOR THE RECORD. Ask your caregiver to keep you apprised of your baby's daily activities while at work.  Baby Tracker journal makes it easy. - Child MagazineIPARENTING MEDIA AWARD Winner.  Top Product Award and Hot Pick,  Just for Mom Category.  - iParenting Media (a division of Disney.com)",
 'Newborn Baby Tracker&reg; - Round the Clock Childcare Journal, Log Book   Baby This is version of the award-winningBaby Trackerseries designed specifically to track and monitor the schedules of NEWBORNS and NURSING moms who need 24-hour (night and day) monitoring.  Time Too\'s simple, day- and night-on-a-page journal uses a charting system of activity by time with simple check boxes and fill-in-the-blanks to record and view feedings, diaper changes and sleep schedules and activities--- creating a visual snapshot of schedules and needs.  Spiral binding allows a 24-hour (day page plus night page) view that can lay flat on any countertop or bedside table with easy portability. A specific column for nursing mothers makes it easy to record and remember time duration of feedings and breast rotation.   Daily pages formatted with additional areas for notes, a daily checklist, baby needs, and daily developmental notes, let the Newborn Baby Tracker- Round the Clock Journal display all important information of the day in a single view.  Additional parent pages keep a Quick Contacts list and Health Facts at your fingertips. Perfect for monitoring nursing and baby sleep schedules, preparing for doctor visits, and making easy hand-offs to other child care helpers.Designed to accommodate 3 months (90 days) of night and day side-by-side tracking.   A perfect gift and true mother\'s helper for the new baby.iPARENTING MEDIA AWARD Winner.  Top Product Award and Hot Pick,  Just for Mom Category.  - iParenting Media (a division of Disney.com)MOM QUOTES:"This product was my sanity saver"  "Almost like having an extra pair of hands" "Helps make for joyful days, and sleep-filled nights"(**PLEASE NOTE:  Other Baby Tracker journals are available in different formats for daily activity tracking with day-only pages to record meals, sleep, changes, play and daily schedules and needs, with age-specific features.  Perfect for working moms using childcare to make drop-offs and pick-ups a breeze)',
 'Fisher Price Nesting Action Vehicles   Baby This colorful car collection develops motor skills and hand-eye coordination while your child makes important discoveries about sorting and strategy. There are four vehicles, numbered 1 through 4, of graduated  sizes: a rattling green sports car, a blue police car with a revolving roof light, a yellow school bus with an opening sunroof, and a red fire truck with an adjustable clicking ladder. The vehicles can be rolled  across the floor, and then stacked--ever so carefully--atop each other, and finally all nested inside the fire truck. Vehicles only nest or stack completely when arranged in proper order of size and number. Made of sturdy plastic, these toys can be dipped in warm sudsy water for easy cleaning.--Kathryn Gustafson',
 'My Quiet Book, Fabric Activity Book for Children   Baby This darling cloth book offers hands-on experience in recognizing shapes,  telling time, buttoning, buckling, snapping, lacing, distinguishing textures, and zipping.  The soft red book measures 8 inches and has a sturdy red zipper around three sides,  with soft stuffed handles on top. Three bright balloons and "My Quiet Book" are  embroidered on the front. Inside are four stiff white fabric-covered pages featuring  eight different activities. There are quilted shapes in primary colors with Velcro  attachments, a clock with movable hands, pastel quilted flowers that button onto their  stems, and bright quilted balloons that snap onto their strings. There\'s a buckle to thread  on a pair of denim shorts, white laces to secure a red and yellow tennis shoe, bright  squares of differently textured fabrics for touching, and a zipper to fasten a floral dress.  Each page is lovingly finished and features a prominently placed embroidered skill title.  This book is great for skill learning at home and even better as a traveling companion!--Tami Horiuchi',
 "The First Years Massaging Action Teether The First Years Baby In a relatively new concept in teething, The First Years  introduces this massaging action teether. The concept is really quite  simple: offer even the youngest infants a means to massage their gums  at will. The massaging action increases circulation, thereby helping to  alleviate swelling and discomfort. This soft, yellow, star-shaped  teether has a smiling face and three nubby points that vibrate when a  child bites down on them. The star sits upon an oversized blue plastic  handle that's easy for even the youngest child to grasp. There's also  an opening at the bottom of the handle that accepts a toy strap. The  star rattle is surface washable and is powered by a nonreplaceable  battery that's sealed inside the teether's handle for maximum safety.--Tami Horiuchi",
 "The First Years Soft Teething Beads The First Years Baby As is the case with pacifiers and bottles, different teethers  please different babies. Having the right one can make all the  difference in the world. These Soft Teething Beads are attached to a  yellow plastic claspless cord. Twelve knobby beads make up the teether  so it's long enough for a baby to grasp with both hands. The beads are  good and knobbly so babies will be able to fully work their gums, and  while holding the chain babies will inadvertently practice gross motor  skills by pulling their hands away from each other. When a baby is done  using this teether it'll make a perfect necklace for dolls or a  counting and color toy.--Sandy Hirsch",
 'Crown Crafts The Original NoJo BabySling by Dr. Sears - Denim   Baby Wear your baby?! Dr. William Sears, noted pediatrician and  author (with his wife Martha, a registered nurse) of child-care books,  includingThe Baby BookandParenting the Fussy Baby,  recommends it highly. His research reveals that parents who "wear" their  babies experience a deep bonding with them; babies cry less when comforted  by the close movement, touch, smell, and sound of a loved one; and such  babies spend more time in a state of "quiet alertness," which is the optimal  state for learning. Designed by Dr. Sears to foster the physical and emotional  closeness of "attachment parenting," the Babysling Cradle lets you carry your  baby (up to 20 pounds) in comfort and safety. The fabric sling with its  extra-padded elastic railing nestles baby in a natural position. Your  warmth and touch do the rest. Four positions (cradle, snuggle, kangaroo, and  hip straddle) accommodate baby and the situation--from nursing to shopping.  The Babysling Cradle comes with an instruction booklet.--Ava Natov',
 "Arm's Reach Original Co-sleeper 100% Cotton White Sheet   Baby Original cotton blend fitted sheet specifically designed for the arm's reach co-sleepers.",
 'Sassy Busy Bugs Bar   Baby The Busy Bug Stroller bar is a portable stroller bar and  activity center for the baby on the move. The colorful soft cloth main  bar is 15 inches long by 2 inches in diameter; Velcro bands allow for  easy positioning in front of your baby on almost any stroller, swing,  or infant seat. There are five activities, including a twirling bug, a  bumblebee atop a twisty plastic stalk, and a crunchy-sounding cloth  butterfly. The most distracting feature might be the removable,  dishwasher-safe snack cup in the center, which has a flip-up,  bug-decorated lid for hiding (or revealing) snacks.--Richard Farr',
 'Baby Trend Diaper Champ   Baby When dealing with a young baby or squirming toddler at diaper changing time, the last thing you need is a diaper pail that requires two hands. The Diaper Champ helps eliminate hassle&#x97;and odor&#x97;by providing convenient one-hand operation for quick disposals.Even better is that this wondrous device takes regular garbage bags. There is no need to constantly buy brand name refills because the Champ can use the typical tall kitchen sack, plus grocery or most other plastic bags. Aside from the use of regular bags making it the economical choice, this feature also makes the Champ more flexible. While diapers will no doubt be the most thrown away item, this pail can also accommodate wipes, cotton swabs, tissues, and other baby essentials.Functionality is simple: drop a diaper (or other trash) into the pail&#x92;s top receptacle and flip the handle. To empty, just unlock the top and remove the bag. Standing about two feet high, the Diaper Champ&#x92;s capacity is on par or larger than many of its competitors, usually only requiring a bag change once a week.But the true test of any diaper pail is its smell control, right? Most moms we polled claimed the Champ the hands-down winner, and only a few had occasional escaped odors after 18+ months of use. Once toddlers have been introduced to solid foods using scented bags can help fight off any excess pail smell. Another great tip for keeping the Champ fresh is to quickly spray it down with a disinfectant when changing bags.']

In [8]:

course_list = df[i_id].tolist()
#sentences = df[desc_str].tolist()

assert course_list[-1] == len(course_list) - 1

In [9]:
# should `pip install sentence_transformers` first
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentence_embeddings = model.encode(sentences)
print('text encoded!')

assert sentence_embeddings.shape[0] == df.shape[0]
np.save(os.path.join(file_path, 'text_feat.npy'), sentence_embeddings)
print('done!')

/home/minhle/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

text encoded!
done!

In [10]:
sentence_embeddings[:10]

array([[-0.07651239, -0.00465495, -0.04175242, ..., -0.02215183,
         0.01199163,  0.03745584],
       [-0.074025  , -0.02081848, -0.0869366 , ...,  0.01936686,
         0.03331775,  0.00943885],
       [-0.02278868,  0.0234328 ,  0.0098731 , ...,  0.04196899,
         0.02564454,  0.10332294],
       ...,
       [-0.04872961,  0.04490934, -0.00986575, ..., -0.0261429 ,
         0.08081724,  0.08468328],
       [-0.00700678, -0.009185  , -0.00793412, ..., -0.00388827,
        -0.02889496,  0.08256401],
       [-0.054946  ,  0.01991389, -0.03054535, ..., -0.03612386,
         0.06067673, -0.03718201]], shape=(10, 384), dtype=float32)

In [11]:
load_txt_feat = np.load('text_feat.npy', allow_pickle=True)
print(load_txt_feat.shape)
load_txt_feat[:10]

(7050, 384)

array([[-0.07651239, -0.00465495, -0.04175242, ..., -0.02215183,
         0.01199163,  0.03745584],
       [-0.074025  , -0.02081848, -0.0869366 , ...,  0.01936686,
         0.03331775,  0.00943885],
       [-0.02278868,  0.0234328 ,  0.0098731 , ...,  0.04196899,
         0.02564454,  0.10332294],
       ...,
       [-0.04872961,  0.04490934, -0.00986575, ..., -0.0261429 ,
         0.08081724,  0.08468328],
       [-0.00700678, -0.009185  , -0.00793412, ..., -0.00388827,
        -0.02889496,  0.08256401],
       [-0.054946  ,  0.01991389, -0.03054535, ..., -0.03612386,
         0.06067673, -0.03718201]], shape=(10, 384), dtype=float32)

# Image encoder (V0)，following LATTICE, averaging over for missed items

In [12]:
df[:5]

,itemID,asin,categories,description,title,price,imUrl,brand,related,salesRank
0,0,097293751X,[['Baby']],Easily keep track of your baby's or child's da...,"Baby Tracker&reg; - Daily Childcare Journal, S...",17.00,http://ecx.images-amazon.com/images/I/41Bb6wf%...,Time Too,"{'also_bought': ['9729375011', 'B004FN1AE8', '...",NaN
1,1,9729375011,[['Baby']],This is version of the award-winningBaby Track...,Newborn Baby Tracker&reg; - Round the Clock Ch...,15.95,http://ecx.images-amazon.com/images/I/51r3BLpL...,,"{'also_bought': ['B000V5KPZ4', 'B001F8TLLU', '...",NaN
2,2,B00000IZQI,[['Baby']],This colorful car collection develops motor sk...,Fisher Price Nesting Action Vehicles,8.37,http://ecx.images-amazon.com/images/I/51E83QCC...,,"{'also_bought': ['B0042D69W4', 'B00428LIZM', '...",NaN
3,3,B00000J3LL,[['Baby']],This darling cloth book offers hands-on experi...,"My Quiet Book, Fabric Activity Book for Children",27.00,http://ecx.images-amazon.com/images/I/51GoNXhB...,,"{'also_bought': ['B00000J3LC', 'B0043G4JOA', '...",NaN
4,4,B00002JV9S,[['Baby']],"In a relatively new concept in teething, The F...",The First Years Massaging Action Teether,8.84,http://ecx.images-amazon.com/images/I/41gVp98n...,The First Years,"{'also_bought': ['B0013FCBJO', 'B0019QCGVK', '...",NaN

In [13]:
import array

def readImageFeatures(path):
  f = open(path, 'rb')
  while True:
    asin = f.read(10).decode('UTF-8')
    if asin == '': break
    a = array.array('f')
    a.fromfile(f, 4096)
    yield asin, a.tolist()

In [18]:

img_data = readImageFeatures(r"../raw_data/image_features_Baby.b")
item2id = dict(zip(df['asin'], df['itemID']))

feats = {}
avg = []
for d in img_data:
    if d[0] in item2id:
        feats[int(item2id[d[0]])] = d[1]
        avg.append(d[1])
avg = np.array(avg).mean(0).tolist()

ret = []
non_no = []
for i in range(len(item2id)):
    if i in feats:
        ret.append(feats[i])
    else:
        non_no.append(i)
        ret.append(avg)

print('# of items not in processed image features:', len(non_no))
assert len(ret) == len(item2id)
np.save('image_feat.npy', np.array(ret))
np.savetxt("missed_img_itemIDs.csv", non_no, delimiter =",", fmt ='%d')
print('done!')

# of items not in processed image features: 63
done!